### ISSUE TITLE
Fatal error 

### ISSUE THREAD

**Issue by abbyarmada** [tkqubo/codeclimate-tslint#37]
A user of Code Climate is experiencing the following error on builds:

```
/usr/src/app/node_modules/tslint/lib/configuration.js:56
        throw new error_1.FatalError("Failed to load " + path + ": " + error.message, error);
        ^

Error
    at new FatalError (/usr/src/app/node_modules/tslint/lib/error.js:40:23)
    at Object.findConfiguration (/usr/src/app/node_modules/tslint/lib/configuration.js:56:15)
    at new TsLinter (/usr/src/app/dist/tsLinter.js:31:57)
    at Object.<anonymous> (/usr/src/app/dist/index.js:22:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

When running Code Climate on the CLI with tslint, they see this error: 
```
Vasas-MacBook-Pro:signalist Vasa$ codeclimate analyze        
Starting analysis
Running tslint: Done!
error: (CC::Analyzer::Engine::EngineTimeout) engine tslint:beta ran for 900 seconds and was killed
```
Any thoughts? cc @kyleholzinger @dblandin

**Comment by kyleholzinger** [comment]
Hm very strange, I haven't seen that one @abbyarmada . What does your tslint config look like?

**Comment by abbyarmada** [comment]
This is a user of Code Climate (I'm the Support Lead) -- let me see if they can chime in/email back.

**Comment by vasagrujic** [comment]
Sure 👉 [Gist](https://gist.github.com/vasagrujic/a2c41b32a0786cd22b77d8c6acc78471)

**Comment by kyleholzinger** [comment]
Sorry, the tslint.json @vasagrujic

**Comment by vasagrujic** [comment]
[tslint.json](https://gist.github.com/vasagrujic/6f19b253f334dc7dd1cc7f50233cd503)

**Comment by vasagrujic** [comment]
I think this is duplicate of #26
