### ISSUE TITLE
Publish?

### ISSUE THREAD

**Issue by sdrioux** [tkqubo/codeclimate-tslint#56]
`tslint-no-circular-imports` was recently added to the package, however, I am still getting errors on Codeclimate when I try to use it.  It looks like 0.6.0 was the last version that was actually published to NPM.  Does that mean that Codeclimate is still using that version?

**Comment by sdrioux** [comment]
@tkqubo bump

**Comment by tkqubo** [comment]
Sorry I have long forgotten doing npm publish.  Now it's updated to 0.10.3.  After you confirm it, I will close this issue.  Thank you! @sdrioux

**Comment by sdrioux** [comment]
Thanks @tkqubo .  I'm still getting the error below.  I'm confused what the issue is at this point, because it seems like the current package version should support "tslint-no-circular-imports".  I'm going to open a ticket with Codeclimate, but if you have any ideas, I'd welcome them.

```
/usr/src/app/node_modules/tslint/lib/configuration.js:55
        throw new error_1.FatalError("Failed to load " + configPath + ": " + error.message, error);
        ^

FatalError: Failed to load /tmp/codeclimate-tslint/ec8e936865e95b8494ce5be590c2aca56749761647e0982a98d6f0d22ecc7d6b.json: Invalid "extends" configuration value - could not require "tslint-no-circular-imports". Review the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_together) for the approximate method TSLint uses to find the referenced configuration file.
    at FatalError.Error (native)
    at new FatalError (/usr/src/app/node_modules/tslint/lib/error.js:27:28)
    at Object.findConfiguration (/usr/src/app/node_modules/tslint/lib/configuration.js:55:15)
    at new TsLinter (/usr/src/app/dist/tsLinter.js:33:57)
    at Object.<anonymous> (/usr/src/app/dist/index.js:28:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/bin/analyze:2:1)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
```
