### ISSUE TITLE
Cannot find tslint-react rule descriptions

### ISSUE THREAD

**Issue by elliterate** [tkqubo/codeclimate-tslint#62]
When trying to use tslint-react, I'm seeing the following error when describing a rule:

```
0: Sorry, description could not be provided due to the internal error:
Error: rule named jsx-alignment is not found in the metadata.
    at IssueConverter.contentBody (/usr/src/app/dist/issueConverter.js:48:19)
    at IssueConverter.convert (/usr/src/app/dist/issueConverter.js:34:28)
    at MapSubscriber._next (/usr/src/app/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/usr/src/app/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/usr/src/app/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
    at Observable._trySubscribe (/usr/src/app/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/usr/src/app/node_modules/rxjs/internal/Observable.js:30:22)
    at MapOperator.call (/usr/src/app/node_modules/rxjs/internal/operators/map.js:32:23)
    at Observable.subscribe (/usr/src/app/node_modules/rxjs/internal/Observable.js:25:31)
    at CatchOperator.call (/usr/src/app/node_modules/rxjs/internal/operators/catchError.js:32:23) [tslint]
```

It looks like it's detecting a violation, but failing when attempting to report on it.

I see this message both locally with the latest Docker images as well as remotely on codeclimate.com.

This is after adding `"tslint-react"` to the `tslint.json` `"extends"` array.

**Comment by tkqubo** [comment]
Since Docker image for codeclimate-tslint has been updated recently (codeclimate/codeclimate-tslint), I think this error has been fixed as well.

https://codeclimate.com/github/tkqubo/codeclimate-tslint-sample/issues?status%5B%5D=&status%5B%5D=open

<img width="864" alt="ss" src="https://user-images.githubusercontent.com/1194760/58000003-62e03780-7b12-11e9-881c-5f5808b0285a.png">

Could you check your project if it works now? @elliterate

**Comment by elliterate** [comment]
Yep! Thanks!
